server:
  port: 8989

management:
  port: 8990
  
info:
  component: Turbine

PREFIX:
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

logging:
  level:
    root: WARN
    com.netflix.discovery: 'OFF'

    # Get info regarding connection to the cofig server and retries if required
    org.springframework.cloud.config.client.ConfigServicePropertySourceLocator: INFO
    org.springframework.retry.support.RetryTemplate: DEBUG

    # org.springframework.integration: DEBUG

    # Set INFO to see the allocated port
    org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer: INFO
    org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer: INFO
    
spring.rabbitmq:
  host: localhost
  port: 5672

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:password@localhost:8761}/eureka/

turbine:
  clusterNameExpression: new String("default")
  appConfig: composite-service
  combineHostPort: true

#turbine:
#  aggregator:
#    clusterConfig: CUSTOMERS
#  appConfig: customers

---
# For deployment in Docker containers
spring:
  profiles: docker

spring.rabbitmq.host: rabbitmq

eureka:
  instance:
    hostname: turbine
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/